apiVersion: v1
kind: Service
metadata:
  name: hello-olympe
  labels:
    app: hello-olympe
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-olympe
    tier: web
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-olympe
  labels:
    app: hello-olympe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-olympe
  template:
    metadata:
      labels:
        app: hello-olympe
        tier: hello-olympe
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-olympe:latest
        name: hello-olympe
        ports:
        - containerPort: 80
          name: hello-olympe
